@host = http://localhost:3000
@token = 

GET {{host}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJleHAiOjE3NTA5MzU1NjgsImlhdCI6MTc1MDMzMDc2OH0.vLc37rg3Ak2LMWoUyv2-f1nmZ6TyT0ybq15GTr3A3o0

###
POST {{host}}/api/users/register
Content-Type: application/json

{
    "nombre": "prueba",
    "apellidos": "prueba",
    "email": "prueba@si.com",
    "password": "12345"
}

###
POST {{host}}/api/users/login
Content-Type: application/json

{
    "email": "prueba@si.com",
    "password": "12345"
}

###
PUT {{host}}/api/users/forgot-password
Content-Type: application/json

{
    "email": "prueba@si.com"
}


###
PUT {{host}}/api/users/reset-password
reset-token: 
Content-Type: application/json

{
    "newPassword": "newPassword"
}

### Catálogo de ejercicios
GET {{host}}/api/exercises
Authorization: {{token}}

###
GET {{host}}/api/exercises/1
Authorization: {{token}}

### Rutinas & rutinas_ejercicios
GET {{host}}/api/routines/
Authorization: {{token}}

###
GET {{host}}/api/routines/1
Authorization: {{token}}

###
GET {{host}}/api/routines/exercises/
Authorization: {{token}}

###
GET {{host}}/api/routines/1/exercises
Authorization: {{token}}

###
PUT {{host}}/api/routines/1
Authorization: {{token}}
Content-Type: application/json

{
  "dificultad_id": 1,
  "metodos_id": 1,
  "nombre": "Rutina actualizada",
  "observaciones": "Observaciones actualizadas"
}

###
POST {{host}}/api/routines/
Authorization: {{token}}
Content-Type: application/json

{
  "dificultad_id": 1,
  "metodos_id": 1,
  "nombre": "Nueva rutina",
  "observaciones": "Observaciones de la rutina"
}

###
POST {{host}}/api/routines/1/exercises
Authorization: {{token}}
Content-Type: application/json

{
  "ejercicios_id": 1,
  "rutinas_id": 1,
  "series": 3,
  "repeticiones": 12
}
