@host = http://localhost:3000
@token = 

GET {{host}}/api/users
Authorization: {{token}}

###
POST {{host}}/api/users/registro
Content-Type: application/json

{
    "username": "",
    "email": "",
    "password": ""
}

###
POST {{host}}/api/users/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###
PUT {{host}}/api/users/forgot-password
Content-Type: application/json

{
    "email": ""
}


###
PUT {{host}}/api/users/reset-password
reset-token: 
Content-Type: application/json

{
    "newPassword": ""
}
