const db = require('../config/db');

// 1 - Obtener los objetivos del usuario y guardarlos en un objeto
// 2 - obtener las rutinas que ha realizado con el objetivos_id que ha guardado en sus preferencias
// y guardamos las rutinas que ha realizado en el objeto
// 3 - Obtenemos las tutinas autogenerated_routine que son las rutinas sugeridas por el sistema
// y las añadimos al array del objeto
// 4 - Devolver de forma aleatoria rutinas que el usuario no ha realizado y tienen el mismo objetivo
// Esto devolvera un id de rutina, que sera la rutina que vamos a devolver al usuario


const autoGenerate = async (id) => {
    const [result] = await db.query('SELECT * FROM grupos_musculares');
    console.log(result, ' - VALOR DE RESULTADO EN MODELO');
    return result;
}

module.exports = {autoGenerate};
