const db = require('../config/db');

// 1 - Obtener los objetivos del usuario y guardarlos en un objeto
// 2 - obtener las rutinas que ha realizado con el objetivos_id que ha guardado en sus preferencias
// y guardamos las rutinas que ha realizado en el objeto
// 3 - Obtenemos las tutinas autogenerated_routine que son las rutinas sugeridas por el sistema
// y las añadimos al array del objeto
// 4 - Devolver de forma aleatoria rutinas que el usuario no ha realizado y tienen el mismo objetivo
// Esto devolvera un id de rutina, que sera la rutina que vamos a devolver al usuario


const objetivosUsuario = async (id) => {
    //Tener encuenta si no tiene objetivos asignados, en ese caso no se le puede generar una rutina
    const [result] = await db.query( 
                `SELECT id, id_usuarios, id_objetivos, fecha
                FROM objetivos_usuarios
                WHERE id_usuarios = ?     
                ORDER by fecha DESC
                LIMIT 1;`, [id]);    
    
    return result;
}

const rutinasRealizadas = async (id) => {
// Rutinas que el usuario ha realizado
    const [result] = await db.query( 
            `SELECT rutinas_id
            FROM rutinas_usuarios
            WHERE usuarios_id = ?
            GROUP by rutinas_id
            ORDER BY rutinas_id ASC;`, [id]);        
    
    return result;
}

const rutinasAutogeneradas = async (id) => {
    //Obtener las rutinas que el usuario han sido sugeridas por el sistema
    const [result] = await db.query(
        `SELECT idrutina
        FROM autogenerated_routine
        WHERE idusuario=?
        GROUP by idrutina
        ORDER BY idrutina ASC;`, [id]);    
        
    return result;
}

const rutinaSugerida = async (obj) => {
    //Sugerimos el id de una rutina que el usuario no ha realizado y que tiene el mismo objetivo
    const { objetivo, rutinas_realizadas } = obj;
   
    const [result] = await db.query(
        `SELECT
            id  
        FROM
            rutinas     
        WHERE
            objetivos_id = ? and id NOT IN (?) 
        ORDER BY
            RAND()    
        LIMIT 1; `, [objetivo,rutinas_realizadas]);    
    
    
    return result[0];
}


const autoGenerate = async (id) => {
   
    //Obtener el objetivo del usuario
    const result = objetivosUsuario(id)

    console.log(result, ' - VALOR DE RESULTADO EN MODELO');
    return result;
}

module.exports = {
    autoGenerate, 
    rutinasRealizadas, 
    objetivosUsuario,
    rutinasAutogeneradas,
    rutinaSugerida
};
